baseURL: https://siavash.askari-nasr.com
disablePathToLower: true
languageCode: en-us
title: Siavash Askari Nasr
permalinks:
  blog: /:section/:year/:month/:day/:filename/
paginate: 15
author:
  name: Siavash Askari Nasr
params:
  Author: CIAvash
  Blog:
    Kind: section
    Title: Blog
    Description: Writings of Siavash Askari Nasr
    Permalink: /blog/
  github: CIAvash
  codeberg: CIAvash
  gitlab: CIAvash
  twitter: CIAvash
  mastodon: '@CIAvash'
  artstation: CIAvash
markup:
  goldmark:
    extensions:
      typographer: false
    parser:
      attribute:
        block: true
  highlight:
    style: doom-one
    anchorLineNos: true
outputFormats:
  RSS:
    baseName: atom
