baseURL = 'https://siavash.askari-nasr.com'
disablePathToLower = true
languageCode = 'en-us'
title = 'Siavash Askari Nasr'

[permalinks]
blog = '/:section/:year/:month/:day/:filename/'

[pagination]
pagerSize = 15

[author]
name = 'Siavash Askari Nasr'

[params]
Author = 'CIAvash'
github = 'CIAvash'
codeberg = 'CIAvash'
gitlab = 'CIAvash'
twitter = 'CIAvash'
mastodon = '@CIAvash'
artstation = 'CIAvash'

[params.Blog]
Kind = 'section'
Title = 'Blog'
Description = 'Writings of Siavash Askari Nasr'
Permalink = '/blog/'

[markup.goldmark.extensions]
typographer = false

[markup.goldmark.parser.attribute]
block = true

[markup.highlight]
style = 'doom-one'
anchorLineNos = true

[outputFormats.RSS]
baseName = 'atom'
